### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: >-
  현재 사용할 수 있는 데 사용할 수 있는 고 비트 수를 반환 합니다.

  사용 되지 않은 비트를 포함 합니다. 즉,에 의해 `GetQubitsAvailableToUse`반환 되는의 비트를 포함 합니다.
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      `borrowing` 문에 할당 될 수 있는 값입니다.

      사용 중인 대상 컴퓨터에서이 정보를 제공 하지 않으면이 반환 `-1` 됩니다.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
metadata:
  ms.openlocfilehash: 99dd2afb66c334b112a2ee511b0437281da6b888
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82682404"
