### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: " # <a name=\"summary\"></a>요약\n 이러한 함수는 퀀텀 계산이 발생 하는 환경에 대 한 정보를 제공 합니다."
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    현재 사용할 수 있는 데 사용할 수 있는 고 비트 수를 반환 합니다.

    사용 되지 않은 비트를 포함 합니다. 즉,에 의해 반환 되는의 비트를 포함 `GetQubitsAvailableToUse` 합니다.
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: 현재 사용할 수 있는 범위의 비트 수를 반환 합니다.
metadata:
  ms.openlocfilehash: 7f597d8f429089b0ebf2c22cef1d1b98ea270402
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89341159"
