### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft 양자 환경
summary: " # <a name=\"summary\"></a>요약\n 이러한 함수는 퀀텀 계산이 발생 하는 환경에 대 한 정보를 제공 합니다."
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    현재 사용할 수 있는 데 사용할 수 있는 고 비트 수를 반환 합니다.

    사용 되지 않은 비트를 포함 합니다. 즉, `GetQubitsAvailableToUse`에서 반환 하는 원하는 비트를 포함 합니다.
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: 현재 사용할 수 있는 범위의 비트 수를 반환 합니다.
ms.openlocfilehash: 50e5cfb7c1b9a4075c25b2705d00b435a09e159e
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 10/30/2019
ms.locfileid: "73056825"
