### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: 현재 사용할 수 있는 데 사용할 수 있는 고 비트 수를 반환 합니다.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: 현재 사용할 수 있는 범위의 비트 수를 반환 합니다.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: 이러한 함수는 퀀텀 계산이 발생 하는 환경에 대 한 정보를 제공 합니다.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 87e1659f8ecdd6df99271f7552f683ffed85b151
  ms.sourcegitcommit: a87c1aa8e7453360025e47ba614f25b02ea84ec3
  ms.translationtype: MT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 11/26/2020
  ms.locfileid: "96201447"
